# Dockerfile-nginx

FROM nginx:alpine

# Nginx will listen on this port
EXPOSE 80

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf
RUN echo "uwsgi_read_timeout 300s;" > /etc/nginx/conf.d/custom_timeout.conf

# We copy the requirements file in order to install
# Python dependencies
COPY app.conf /etc/nginx/conf.d